spring:
  datasource:
    url: 'jdbc:h2:file:./build/data/testdb'
    driverClassName: 'org.h2.Driver'
    username: sa
    password: password
  output:
    ansi:
      enabled: always
  sql:
    init:
      mode: always
      schema-locations: 'classpath:sql/schema.sql'