spring:
  datasource:
    url: 'jdbc:h2:file:./build/data/testdb'
    driverClassName: 'org.h2.Driver'
    username: 'sa'
    password: ''
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: 'org.hibernate.dialect.H2Dialect'
  h2:
    console:
      enabled: true